### ISSUE TITLE
How to make money with your Python Open-Source Project

### ISSUE THREAD

**Issue by Honzin** [maxtepkeev/talks#1]
Please can you add your talk _How to make money with your Python Open-Source Project_ from Euro Python.

**Comment by maxtepkeev** [comment]
Hi, this repo is just for the code that was used in the talk if any.

Slides for the talk are [here](https://www.slideshare.net/maxtepkeev/europython-2017-how-to-make-money-with-your-python-opensource-project).
The video is available [here](https://www.youtube.com/watch?v=dyRDmcsTwhE&feature=youtu.be&t=6h52m30s) until they cut individual videos from it.
